# Welcome to Jekyll!
administrator:
  email: jan.brandejs@pirati.cz, jan.suchanek@gmail.com
github:
  url: https://github.com/pirati-web/praha9.pirati.cz/
  branch: master
url: "https://praha9.pirati.cz"

mediaStorage: praha9

title: "Piráti Praha 9"
description: "Česká pirátská strana - místní sdružení Praha 9"
keywords: "Piráti, česká pirátská strana, svoboda, demokracie, Piráti Praha 9, Prosek, Vysočany, Libeň, Krocínka, Hrdlořezy"

organization:
  name: MS Piráti Praha 9
  shortName: Piráti Praha 9
  email: praha9@pirati.cz
  daonetelink: https://dary.pirati.cz/podpor-kraj/praha/adresne-dary-pro-ks-praha/?p=110109
  contactUid: kornelia.gottmannova
  phone: +420 777 065 665
  address: |
    Na Moráni 3
    120 00 Praha 2
  #residenceImg: miscellaneous.jpg
  mapLink: https://mapy.cz/s/2N7Yv
  redmineLink: https://redmine.pirati.cz/projects/praha-9
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  transparentAccountSpecificSymbol: 110109
  onboardingLink: https://nalodeni.pirati.cz/

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite

calendar:
  id: p4idl4uviv7t2c85gfq51lia9k@group.calendar.google.com
  title: "Kalendář Pirátů Prahy 9"
  page: "https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=p4idl4uviv7t2c85gfq51lia9k%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3"

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/PiratiPraha9/"
  profilePageName: "Piráti Praha 9"
  appId: 1526197851008996

matomo:
  loadSDK: true
  siteId: 68

forum:
  page: https://forum.pirati.cz/viewforum.php?f=1438

youtube:
  channel: UC_zxYLGrkmrYazYt0MzyVlA

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  #profilePage: 

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

styleguide_base_url: 'https://styleguide.pirati.cz/latest'

############### SETTINSG #################

theme: jekyll-theme-pirati

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati

pagination:
  per_page: 9
  permalink: '/:num/'
  title: ':title - stránka :num'
  trail: 7

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - vendor

permalink: /tiskove-zpravy/:title/
collections:
  people:
    output: true
    permalink: /clenove/:path:output_ext
  program:
    output: true
    permalink: /volby/:path:output_ext

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/js
    - assets/img
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-8.4.1/assets/img
